<?php

namespace App\Filament\Resources\PlanningsResource\Pages;

use App\Filament\Resources\PlanningsResource;
use App\Models\Customers;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListPlannings extends ListRecords
{
    protected static string $resource = PlanningsResource::class;

    protected function getHeaderActions(): array
    {
        return [
//            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return Customers::query()->where('status', 1); // TODO: Change the autogenerated stub
    }
}
