<?php

namespace App\Filament\Resources\CandidatesResource\Pages;

use App\Filament\Resources\CandidatesDuringRecruitmentResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditDuringRecruitmentCandidates extends EditRecord
{
    protected static string $resource = CandidatesDuringRecruitmentResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function getRedirectUrl(): ?string
    {
        return CandidatesDuringRecruitmentResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
