<?php

namespace App\Filament\Resources;

use App\Filament\Resources\CitiesResource\Pages;
use App\Filament\Resources\CitiesResource\RelationManagers;
use App\Models\Cities;
use App\Models\Countries;
use Filament\Forms;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use HusamTariq\FilamentDatabaseSchedule\Filament\Columns\ActionGroup;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class CitiesResource extends Resource
{
    protected static ?string $model = Cities::class;
    protected static ?string $navigationGroup ='Settings';
    protected static ?string $navigationIcon = 'heroicon-o-map';
    protected static ?int $navigationSort = 5;
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('name')
                    ->label(__('admin_settings.name'))
                    ->unique()
                    ->validationMessages(['unique'=>'City name already exists.'])
                    ->required(),
                Forms\Components\Select::make('country_id')
                    ->label(__('admin_settings.country'))
                    ->options(Countries::all()->pluck('name','id'))
                    ->required()
            ])->columns(1);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultPaginationPageOption(50)
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('admin_settings.name'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('country.name')
                    ->label(__('admin_settings.country'))

            ])

            ->defaultSort('name','asc')
            ->filters([
                //
            ])
            ->actions([
                ActionGroup::make([
                    Tables\Actions\EditAction::make()
                        ->slideOver()
                        ->modalWidth('md'),
                    Tables\Actions\DeleteAction::make()
                ]),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListCities::route('/'),
//            'create' => Pages\CreateCities::route('/create'),
//            'edit' => Pages\EditCities::route('/{record}/edit'),
        ];
    }

    public static function getNavigationLabel(): string
    {
        return __('admin_settings.cities');
    }

    public static function getNavigationGroup(): ?string
    {
        return __('admin_settings.settings');
    }

    public static function getPluralLabel(): ?string
    {
        return __('admin_settings.cities'); // TODO: Change the autogenerated stub
    }
}
