<?php

namespace App\Filament\Resources;

use App\Filament\Resources\LanguagesResource\Pages;
use App\Filament\Resources\LanguagesResource\RelationManagers;
use App\Models\Language;
use Filament\Actions\DeleteAction;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use HusamTariq\FilamentDatabaseSchedule\Filament\Columns\ActionGroup;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use function Laravel\Prompts\select;

class LanguagesResource extends Resource
{
    protected static ?string $model = Language::class;

    protected static ?string $navigationIcon = 'heroicon-o-language';

    protected static ?string $navigationGroup = 'Settings';

    protected static ?int $navigationSort = 5;
    public static function form(Form $form): Form
    {
        return $form
            ->schema([]);
    }

    public static function table(Table $table): Table
    {
        return $table->defaultPaginationPageOption(50)
            ->defaultSort('name')
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('admin_settings.name'))
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                ActionGroup::make([
                    Tables\Actions\EditAction::make()
                        ->tooltip('Edit')
                        ->form(self::getFormSchema())
                        ->slideOver()
                        ->modalWidth('sm'),
                    Tables\Actions\DeleteAction::make()
                        ->tooltip('Delete')
                ])
            ])
            ->bulkActions([
//                Tables\Actions\BulkActionGroup::make([
//                    Tables\Actions\DeleteBulkAction::make(),
//                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make()
                    ->form(self::getFormSchema())
                    ->slideOver()
                    ->modalWidth('sm'),
            ])
            ;
    }

    public static function getFormSchema()
    {
        return [
            Forms\Components\TextInput::make('name')
                ->label(__('admin_settings.name')),
        ];
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListLanguages::route('/'),
        ];
    }

    public static function getNavigationLabel(): string
    {
        return __('admin_settings.languages');
    }

    public static function getNavigationGroup(): ?string
    {
        return __('admin_settings.settings');
    }

    public static function getPluralLabel(): ?string
    {
        return __('admin_settings.languages'); // TODO: Change the autogenerated stub
    }
}
